{% set version = "0.0.1" %}
{% set commit = "474a3a49fe3b3dca859f69a6173263018dd2d34c" %}

package:
  name: mplexporter
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/mpld3/mplexporter/archive/{{ commit }}.tar.gz
  sha256: a92c5b634e2c4f241022c7600c31984edc515508450940892823c7fe2197e9d0

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base

test:
  imports:
    - mplexporter

about:
  home: https://github.com/mpld3/mplexporter
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'General Matplotlib Exporter'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
