{% set version = "0.0.1" %}
{% set commit = "577609a60a9680b0114b4576cd0efaebdc59280d" %}

package:
  name: mplexporter
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/mpld3/mplexporter/archive/{{ commit }}.tar.gz
  sha256: a92c5b634e2c4f241022c7600c31984edc515508450940892823c7fe2197e9d0

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - matplotlib

test:
  imports:
    - mplexporter

about:
  home: https://github.com/mpld3/mplexporter
  license: BSD 3-Clause
  summary: 'General Matplotlib Exporter.'

extra:
  recipe-maintainers:
    - jakevdp
    - ocefpaf
