travis:
  secure:
    BINSTAR_TOKEN: DIqspQqJVEFBCV5dycSaqLg3dGOXlp1YD+a9VRy6i3OVraYXf7d/OiBxPplgwHgkrt8tfrO6TG6MGoJUczXRDzYbO1YnvcZYSbOeAbophQqiwZZV115UrwGsUNU8k75IpczL1aOu23Yb3+mX+gxw8Ys3h/e/5mPmqO2DmxOCVQWnSnYFp90X/NX1bo+WWqM/W6zhygsto9+DYpBUh0HMPd7COkTQq2WdWwwc+U1UA4HSpC+HmEJi4a0u7MyZ7OPbB/LqGfVOA0vZGDJSDNXfpv4in1z7lByAhpcvrXnNYF+daae3tkCV/P0xsVNOtoBOoZIXwTp4UFbmQmrHkrL16lcP7blhMKWFYP58dgkhcaIkG21kSrWeMIXaHAAiZtprifkakUHVPhqy+caHqECpdVtEG4OPFdRAcKuA76IH0lZehgT+Spl9kQxX4DSDfVTSCm7P9JHQ/uEsWSIEsouOaozgL2V3WLheehlBbh9Ru2G8QaP7p3tlwWtPvDNp/y5jVikHDi7YdwjQTRfVN9dRiVRhcgX9f53wvVOeedhD8M8MwYyngRud1xOuAxTpzIkcF+iHyUonor5tQzRznOgqpW5jQw9PI6lUz/wp0AwelUKGcgGPjFdLDdxpO402uxuTIogAQoWcLxT5KHPSkyT7keEil8sgFaV/V6r/gRS6PZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
