travis:
  secure:
    BINSTAR_TOKEN: bX+cXy30QXCKp99xu1ErJGyPJYZoM7NQOKwgWe2/HEJWXsK3zdThW34tQRQZP+zujjGq1jT0qOXDJhJtf3oh/8e0Zmp1cr82M3AbF4j/b8VZAtDfZXNNzn7Qg6RKUro3J59I7GHM42KbvJXvLbfZl18tL1aGd8saNMXYAmL5kg+ddsX4p7K4qLoLswAqB4sfqvv6bPqaYaG4FYVGre3jrE7ylt15R928n/8RoPhS8FueepPevjX1N22FdClJFxu+cqI5/mduOp5PQLPMv1so05cu0knHMOI1KoxhQctI1xIA5Ej73wytaPWyBOTkIzmOGgRpDARlIapPDknsQ20aPDwus1ODr3ZQ0lnKJQrIPhT11/KPnIo86aeu4Nl+/zXj/6mxoOE94iaMoUivkPT2+tTpK6+WBQe+6SVro8IeyLl2v8lcntuOTXYV4WOa2Ri2NosXfipSGLLfJmQU67odaiDPL1j/nx67gPxT1fxHSA3qeFOiEuUgxhdCBPHa5MXsyxjJM4hZtDxWM9TL9Z58jzrbBV5NT5kOc59/8TjSkCNOBVcodFMg//bQZ+e6Y4ca0AQ2tp4xa9JbaemE6QF4A+OvSuRktVBVLvkxpKq4uJoODAQ8HRAoC5jVpr4KPKQ3PHc65emrr1nWciF61gsZg9CtL9bqTkZyVx62+g4ZRMM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
